name: "01_Terraform"
on:
  workflow_dispatch:

jobs:
  branch_name:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print branch
      run:  echo ${GITHUB_REF##*/}
  Plan_Dev:
    if: github.ref == 'refs/heads/develop'
    uses: pratyusha-deekshit/protected_cred_terraform/.github/workflows/genesys_tf_plan.yml@develop
    with:
      gh_environment: dev
    secrets:
      client_id: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID_TEST }}
      client_secret: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET_TEST }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: pratyusha-deekshit/protected_cred_terraform/.github/workflows/genesys_tf_apply.yml@develop
    with:
      gh_environment: dev
    secrets:
      client_id: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID_TEST }}
      client_secret: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET_TEST }}

  Plan_Prod:
    if: github.ref == 'refs/heads/master'
    uses: pratyusha-deekshit/protected_cred_terraform/.github/workflows/genesys_tf_plan.yml@master
    with:
      gh_environment: prod
    secrets:
      client_id: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID_TEST }}
      client_secret: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET_TEST }}

  Deploy_Prod:
    needs: Plan_Prod
    uses: pratyusha-deekshit/protected_cred_terraform/.github/workflows/genesys_tf_apply.yml@master
    with:
      gh_environment: prod
    secrets:
      client_id: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID_TEST }}
      client_secret: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET_TEST }}
